FROM openjdk:8u111-jdk AS builder
WORKDIR source
ARG JAR_FILE=target/demo*.jar
COPY ${JAR_FILE} application.jar
RUN java -Djarmode=layertools -jar application.jar extract

FROM openjdk:8u111-jdk
WORKDIR application
COPY --from=builder source/dependencies ./
COPY --from=builder source/spring-boot-loader ./
COPY --from=builder source/snapshot-dependencies ./
COPY --from=builder source/application ./
ENTRYPOINT ["java", "org.springframework.boot.loader.JarLauncher"]
